include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**.g.dart"

linter:
  rules:
    # ------ Disabling individual rules. ----- #
    # Muting the `prefer_constructors_over_static_methods` linter rule is
    # necessary here because:
    #  1. The `of` method's purpose in
    # `static Configs of(BuildContext context)` is to provide a statically
    # accessible method to retrieve the inherited widget instance.
    #  2. This pattern is widely used and recognized in Flutter's architecture
    #     for managing inherited data.
    #  3. Following the linter rule would contradict the best practices and
    #     conventions established in the Flutter framework.
    prefer_constructors_over_static_methods: false
    avoid_web_libraries_in_flutter: false

    # ------------------------------------- #

    # ------ Enabling individual rules. ---- #
    #                 ---                   #
    # These rules here are good but too ----#
    # opinionated to enable them by default. #
    # ------------------------------------- #
    require_trailing_commas: true
    use_key_in_widget_constructors: true
    sort_pub_dependencies: true
    prefer_const_constructors_in_immutables: true
    avoid_classes_with_only_static_members: true
    # Make constructors the first thing in every class.
    sort_constructors_first: true
    always_put_required_named_parameters_first: true
    prefer_single_quotes: true

    # Blindly follow the Flutter code style, which prefers types everywhere.
    always_specify_types: true

    # Do not allow code lines longer than 80 characters.
    lines_longer_than_80_chars: true
